FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY SistemaRepuestosMaquinas.sln ./
COPY SistemaRepuestosMaquinas.Web/SistemaRepuestosMaquinas.Web.csproj SistemaRepuestosMaquinas.Web/
COPY SistemaRepuestosMaquinas.Common/SistemaRepuestosMaquinas.Common.csproj SistemaRepuestosMaquinas.Common/
RUN dotnet restore SistemaRepuestosMaquinas.Web/SistemaRepuestosMaquinas.Web.csproj

COPY . .
RUN dotnet publish SistemaRepuestosMaquinas.Web/SistemaRepuestosMaquinas.Web.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "SistemaRepuestosMaquinas.Web.dll"]
