<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SistemaRepuestosMaquinas.Entity\SistemaRepuestosMaquinas.Entity.csproj" />
    <ProjectReference Include="..\SistemaRepuestosMaquinas.Common\SistemaRepuestosMaquinas.Common.csproj" />
    <ProjectReference Include="..\SistemaRepuestosMaquinas.Data\SistemaRepuestosMaquinas.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.6.2" />
  </ItemGroup>
</Project>
